use_frameworks!

platform :ios, '9.0'

target 'AZLUtil_Example' do
  pod 'AZLUtil', :path => '../'

  target 'AZLUtil_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
